### ISSUE TITLE
Genie podman container crashing on startup

### ISSUE THREAD

**Issue by jleonardfl** [stanford-oval/genie-server#284]
[genie-podman.log](https://github.com/stanford-oval/almond-server/files/7491346/genie-podman.log)
[2021-11-06T22_23_23_739Z-debug.log](https://github.com/stanford-oval/almond-server/files/7491355/2021-11-06T22_23_23_739Z-debug.log)

Maybe a noob permissions problem since I'm not well versed with podman.  After snowboy init, some `Home directory not accessible: Permission denied` errors come up before genie sys_greet and a npm crash.

**Comment by gcampax** [comment]
Hi @jleonardfl , thanks for your report!

We merged a pretty significant rework of the voice-support code in the almond-server container in the last few days. Would you be able to test if the error still occurs?

**Comment by jleonardfl** [comment]
Just pulled the newest image and it started up like a charm!
