### ISSUE TITLE
Installation instructions contain errors

### ISSUE THREAD

**Issue by andy8025** [stanford-oval/genie-server#304]
Great project, but as a n00b trying to install Genie for the first time, I came across some errors/typos in installation instructions.

https://wiki.genie.stanford.edu/getting-started/installation-guide/standalone-server
https://github.com/stanford-oval/genie-server

First, both URLs above links to podman.io installation instructions. The Ubuntu instructions on podman.io don't work (e.g. contain nonsensical commands like ". /etc/os-release")

Second, on https://wiki.genie.stanford.edu/getting-started/installation-guide/standalone-server there is a typo in:

podman run --name genie -p 3000:3000 \
    -v /dev/shm:/dev/shm \
    -v $XDG_RUNTIME_DIR/pulse:/run/pulse \
    v $XDG_CONFIG_HOME/genie-server:/var/lib/genie-server \
    --security-opt label=disable \
    stanfordoval/almond-server:latest

I'm guessing the fourth line should start with -v

Third, the podman command shown on https://wiki.genie.stanford.edu/getting-started/installation-guide/standalone-server is different than the podman command on https://github.com/stanford-oval/genie-server

**Comment by gcampax** [comment]
If you find an error in your wiki, apologies, feel free to fix it, the wiki is editable by anyone with a Github account. I corrected the wiki now and both wiki and readme have the same instructions.

As for the podman install instructions, I recommend you report the problem to the podman developers.
