### ISSUE TITLE
Running into npm error message on the Pinephone with podman version

### ISSUE THREAD

**Issue by petrisch** [stanford-oval/genie-server#307]
Hi there

On UT Edition with 3Gb RAM running mobian:unstable/bookworm.

``sudo apt install podman``

Then tried both the ``/var/lib/genie`` and ``~/.config`` version.
The later gave me this error after getting the image installed:

``{"msg":"exec container process `/usr/bin/npm`: Exec format error","level":"error","time":"2022-01-23T15:25:25.000197416Z"}``

Do I need to install npm as well for some reason?
I'm pretty bad with containers though, so need a little help here :smile:

**Comment by joerg65** [comment]
I had the same and I learned that the pulled container is not for arm64 architecture. Need to follow the steps on the read.me to compile it from source. After that with podman:
`podman run --name genie -p 3000:3000     -v /dev/shm:/dev/shm     -v $XDG_RUNTIME_DIR/pulse:/run/pulse     -e PULSE_SERVER=unix:/run/pulse/native     -v $XDG_CONFIG_HOME/genie-server:/var/lib/genie-server     --security-opt label=disable   localhost/genie-server
`
And if podman says that the name genie already is in use, just` podman rm ...`

**Comment by TomasMonkevic** [comment]
It's crazy that the Genie team advertises everywhere in docs that it's compatible with pis and don't even have a docker image compatible with ARM

**Comment by petrisch** [comment]
doesn't seem to be active so no sense to keep open
