### ISSUE TITLE
Docker port mapping websocket errors

### ISSUE THREAD

**Issue by Guigxs** [stanford-oval/genie-server#308]
Hi, 
I'm trying to install genie-server on my desktop with docker. But I'm facing some websocket errors while mapping the host port 3001 to the container port 3000.

Any idea how to fix ? 

That's my docker command: 
`docker run --name genie-server -p 3001:3000 stanfordoval/almond-server:latest `

genie-server on port 3001:
![image](https://user-images.githubusercontent.com/44777000/151601003-e0eaf3ef-88fa-4569-8177-e1d4d42710b0.png)

genie-server on port 3000:
![image](https://user-images.githubusercontent.com/44777000/151601332-f5498fc8-2e6e-4a25-90a1-26d3492bfa15.png)

**Comment by gcampax** [comment]
To prevent cross-origin connections (which would be insecure), the server checks that the Origin header sent by the browser corresponds to the combination of host and port used by the browser. Hence, what you're trying to do is not possible directly.
If you want to run genie-server on a different port, you must set the PORT environment variable in the container to 3001 and map port 3001 to 3001 in the container.

**Comment by Guigxs** [comment]
That makes sens, thanks !
